var DATABASE = {
  users:[
         {
            "user_id": "2",
            "credentials": "0",
            "password": "b690bc2447d40ea8a6f78345eb979a28",
            "username": "jorass",
            "first_name": "Jory",
            "last_name": "Assies",
            "email": "jory.assies@it.uu.se",
            "phone": "0704811411"
        },
        {
            "user_id": "28",
            "credentials": "3",
            "password": "b612f428e4a53386fdb98f6c2164c16c",
            "username": "sulstr",
            "first_name": "Sulayman",
            "last_name": "Street",
            "email": "sulayman.street@it.uu.se",
            "phone": "0701517627"
        },
        {
            "user_id": "27",
            "credentials": "3",
            "password": "c0d9251f9af5e7410c6a3932f696c449",
            "username": "orapan",
            "first_name": "Orabela",
            "last_name": "Panders",
            "email": "orabela.panders@it.uu.se",
            "phone": "0701503294"
        },
        {
            "user_id": "26",
            "credentials": "3",
            "password": "4ec434994decffa3005b477cc7f992e6",
            "username": "kenolg",
            "first_name": "Kenan",
            "last_name": "Olguin",
            "email": "kenan.olguin@it.uu.se",
            "phone": "0706569560"
        },
        {
            "user_id": "25",
            "credentials": "0",
            "password": "971299fa95fe467db26e8bf01864d48d",
            "username": "saskru",
            "first_name": "Sa\u0161a",
            "last_name": "Kr\u00fcger",
            "email": "sasa.kruger@it.uu.se",
            "phone": "0705349276"
        },
        {
            "user_id": "24",
            "credentials": "0",
            "password": "2a3db2cc165057da53ef13a348e9787f",
            "username": "ervtod",
            "first_name": "Ervin",
            "last_name": "Todd",
            "email": "ervin.todd@it.uu.se",
            "phone": "0702339018"
        },
        {
            "user_id": "23",
            "credentials": "3",
            "password": "743444f0ff666f1f90580e7bc3af5099",
            "username": "aqulyn",
            "first_name": "Aquilina",
            "last_name": "Lyndon",
            "email": "aquilina.lyndon@it.uu.se",
            "phone": "0702611287"
        },
        {
            "user_id": "22",
            "credentials": "3",
            "password": "fc4fd22287923f3b47b91fc5f0a85af5",
            "username": "lasnic",
            "first_name": "Lasse",
            "last_name": "Nicholson",
            "email": "lasse.nicholson@it.uu.se",
            "phone": "0703238992"
        },
        {
            "user_id": "21",
            "credentials": "3",
            "password": "849d51ea793c93194952478aa85694af",
            "username": "maihon",
            "first_name": "Maiken",
            "last_name": "Honda",
            "email": "maiken.honda@it.uu.se",
            "phone": "0709533955"
        },
        {
            "user_id": "20",
            "credentials": "0",
            "password": "739d0d428ff99dc043e8955b5a4885bc",
            "username": "hirchr",
            "first_name": "Hiram",
            "last_name": "Christopherson",
            "email": "hiram.christopherson@it.uu.se",
            "phone": "0709599269"
        }
  ],
  bought: [
    {
      transaction_id: "328",
      admin_id: "25",
      beer_id: "1152803",
      amount: "4",
      price: "24.90",
      timestamp: "2014-10-02 16:05:21"
    },
    {
      transaction_id: "329",
      admin_id: "25",
      beer_id: "1128101",
      amount: "2",
      price: "20.60",
      timestamp: "2014-10-02 16:05:33"
    }
  ],
  sold: [
    
	{
    "transaction_id": "1186",
    "user_id": "2",
    "beer_id": "665836",
    "timestamp": "2014-10-10 19:04:13"
}, {
    "transaction_id": "1187",
    "user_id": "25",
    "beer_id": "765531",
    "timestamp": "2014-10-10 19:36:43"
}, {
    "transaction_id": "1188",
    "user_id": "2",
    "beer_id": "828794",
    "timestamp": "2014-10-10 19:46:18"
}, {
    "transaction_id": "1189",
    "user_id": "25",
    "beer_id": "89547",
    "timestamp": "2014-10-10 20:06:52"
}, {
    "transaction_id": "1190",
    "user_id": "83",
    "beer_id": "722671",
    "timestamp": "2014-10-10 20:18:32"
}, {
    "transaction_id": "1191",
    "user_id": "2",
    "beer_id": "802465",
    "timestamp": "2014-10-10 20:33:43"
}, {
    "transaction_id": "1192",
    "user_id": "25",
    "beer_id": "722671",
    "timestamp": "2014-10-10 20:34:45"
}, {
    "transaction_id": "1193",
    "user_id": "21",
    "beer_id": "731007",
    "timestamp": "2014-10-10 21:07:57"
}, {
    "transaction_id": "1194",
    "user_id": "21",
    "beer_id": "799576",
    "timestamp": "2014-10-10 21:08:08"
}, {
    "transaction_id": "1195",
    "user_id": "21",
    "beer_id": "800523",
    "timestamp": "2014-10-10 21:09:04"
}, {
    "transaction_id": "1196",
    "user_id": "21",
    "beer_id": "802465",
    "timestamp": "2014-10-10 21:09:16"
}
	
  ],
  account: [
    {
      user_id: "2",
      creditSEK: "3000"
    },
    {
      user_id: "27",
      creditSEK: "900"
    },
    {
      user_id: "28",
      creditSEK: "1200"
    }
    
  ],
 // these are the inital quantities
  inventory: [
    {
      nr: "1004703",
      quantity: 1
    },
    {
      nr: "1101003",
      quantity: 1
    },
    {
      nr: "1101101",
      quantity: 4
    },
    {
      nr: "1104103",
      quantity: 3
    },
    {
      nr: "1104203",
      quantity: 6
    },
    {
      nr: "1104803",
      quantity: 8
    },
    {
      nr: "1107109",
      quantity: 15
    },
    {
      nr: "8945803",
      quantity: 19
    },
    {
      nr: "8954701",
      quantity: 10
    },
    {
      nr: "8954801",
      quantity: 8
    },
    {
      nr: "8954901",
      quantity: 10
    },
    {
      nr: "8955501",
      quantity: 16
    },
    {
      nr: "8960906",
      quantity: 10
    },
    {
      nr: "8961108",
      quantity: 10
    },
    {
      nr: "7637201",
      quantity: 10
    },
    {
      nr: "7638601",
      quantity: 10
    },
    {
      nr: "7799701",
      quantity: 20
    },
    {
      nr: "3036004",
      quantity: 13
    },
    {
      nr: "8303202",
      quantity: 11
    },
    {
      nr: "8653401",
      quantity: 10
    },
    {
      nr: "8653604",
      quantity: 10
    },
    {
      nr: "8654202",
      quantity: 10
    },
    {
      nr: "8654301",
      quantity: 10
    },
    {
      nr: "8654402",
      quantity: 10
    },
    {
      nr: "8655002",
      quantity: 10
    },
    {
      nr: "8655101",
      quantity: 10
    },
    {
      nr: "8655201",
      quantity: 10
    },
    {
      nr: "8655401",
      quantity: 10
    }
  ],
  orders: [
    {
      order_id: "o1",
      user_id: "",
      beverages: [],
      totalAmount: 0
    },
    {
      order_id: "o2",
      user_id: "",
      beverages: [],
      totalAmount: 0
    },
    {
      order_id: "o3",
      user_id: "",
      beverages: [],
      totalAmount: 0
    }
  ],
  cart: [],
};

let BEVERAGES = {
  beers: [
    {
      nr: "1004703",
      articleid: "723841",
      articletype: "10047",
      name: "Nils Oscar",
      name2: "Celebration Ale",
      priceinclvat: "43.70",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-02-01",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Ale",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Sverige",
      producer: "Nils Oscar Company",
      provider: "The Nils Oscar Company AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "9.4%",
      module: "T5",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1101003",
      articleid: "665836",
      articletype: "11010",
      name: "Corsendonk Christmas Ale",
      name2: "",
      priceinclvat: "20.90",
      volumeml: null,
      priceperlitre: null,
      introduced: "2012-11-15",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Ale",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Belgien",
      producer: "Brouwerij Corsendonk",
      provider: "AB Wicked Wine Sweden",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "8.1%",
      module: "",
      assortment: "TSS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1101101",
      articleid: "765531",
      articletype: "11011",
      name: "Ayinger",
      name2: "Winter-Bock",
      priceinclvat: "30.40",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-11-15",
      finaldelivery: " ",
      category: "\u00c3\u2013l, M\u00c3\u00b6rk lager",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Tyskland",
      producer: "Brauerei Aying",
      provider: "Brill & Co AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "6.7%",
      module: "",
      assortment: "TSS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1104103",
      articleid: "721327",
      articletype: "11041",
      name: "Sm\u00c3\u00b6rpundet Porter",
      name2: "",
      priceinclvat: "25.80",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-02-01",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Porter och Stout",
      packaging: "Flaska",
      captype: "",
      countryoforigin:
        "Stockholms l\u00c3\u00a4n, Nyn\u00c3\u00a4shamns kommun",
      countryoforiginlandname: "Sverige",
      producer: "Nyn\u00c3\u00a4shamns \u00c3\u2026ngbryggeri AB",
      provider: "Nyn\u00c3\u00a4shamns \u00c3\u2026ngbryggeri AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "5.9%",
      module: "T5",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1104203",
      articleid: "828794",
      articletype: "11042",
      name: "Caspers Schwarz",
      name2: "S:t Eriks Bryggeri",
      priceinclvat: "19.90",
      volumeml: null,
      priceperlitre: null,
      introduced: "2014-05-02",
      finaldelivery: " ",
      category: "\u00c3\u2013l, M\u00c3\u00b6rk lager",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Sverige",
      producer: "S:t Eriks Bryggeri",
      provider: "Galatea Spirits AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "5.1%",
      module: "",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1104803",
      articleid: "722671",
      articletype: "11048",
      name: "Suruga Bay",
      name2: "Imperial IPA",
      priceinclvat: "59.90",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-04-02",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Ale",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Japan",
      producer: "Baird Brewing Co",
      provider: "Cask Sweden AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "7.5%",
      module: "T7",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "1107109",
      articleid: "731007",
      articletype: "11071",
      name: "St\u00c3\u00b6rtebeker Provsmakarl\u00c3\u00a5da",
      name2: "",
      priceinclvat: "130.50",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-03-01",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Flera typer",
      packaging: "6 flaskor \u00c3\u00a0 500 ml",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Tyskland",
      producer: "St\u00c3\u00b6rtebeker Braumanufaktur",
      provider: "Heba Food & Beverages AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "4.9%",
      module: "",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8945803",
      articleid: "601554",
      articletype: "89458",
      name: "Samuel Adams",
      name2: "Imperial White",
      priceinclvat: "33.30",
      volumeml: null,
      priceperlitre: null,
      introduced: "2011-09-01",
      finaldelivery: " ",
      category: "\u00c3\u2013l, Vete\u00c3\u00b6l",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "USA",
      producer: "Boston Beer Company",
      provider: "Galatea Spirits AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "10.3%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    }
  ],
  wines: [
    {
      nr: "8954701",
      articleid: "304865",
      articletype: "89547",
      name: "Scrubby Rise",
      name2: "Sauvignon Blanc Semillon Viognier",
      priceinclvat: "132.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2008-02-01",
      finaldelivery: " ",
      category: "Vitt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "South Australia, McLaren Vale",
      countryoforiginlandname: "Australien",
      producer: "Wirra Wirra Vineyards",
      provider: "Carovin AB",
      productionyear: "2010",
      testedproductionyear: "",
      alcoholstrength: "13%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8954801",
      articleid: "304868",
      articletype: "89548",
      name: "Urano",
      name2: "Cabernet Sauvignon",
      priceinclvat: "126.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2008-02-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Cuyo, Mendoza, Luj\u00c3\u00a1n de Cuyo",
      countryoforiginlandname: "Argentina",
      producer: "Eral Bravo",
      provider: "Carovin AB",
      productionyear: "2009",
      testedproductionyear: "",
      alcoholstrength: "14%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8954901",
      articleid: "304871",
      articletype: "89549",
      name: "Urano",
      name2: "Malbec",
      priceinclvat: "126.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2008-02-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Cuyo, Mendoza",
      countryoforiginlandname: "Argentina",
      producer: "Eral Bravo",
      provider: "Carovin AB",
      productionyear: "2010",
      testedproductionyear: "",
      alcoholstrength: "14%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8955501",
      articleid: "305289",
      articletype: "89555",
      name: "Petit Chablis",
      name2: "",
      priceinclvat: "149.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2008-02-01",
      finaldelivery: " ",
      category: "Vitt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Bourgogne, Chablis, Petit Chablis",
      countryoforiginlandname: "Frankrike",
      producer: "Lup\u00c3\u00a9 Cholet",
      provider: "janake wine group AB",
      productionyear: "2012",
      testedproductionyear: "",
      alcoholstrength: "12.5%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8960906",
      articleid: "596695",
      articletype: "89609",
      name: "Escapades",
      name2: "Cabernet Sauvignon",
      priceinclvat: "299.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2011-08-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Magnum",
      captype: "",
      countryoforigin: "Western Cape, Coastal Region, Stellenbos",
      countryoforiginlandname: "Sydafrika",
      producer: "Escapade Winery",
      provider: "Carovin AB",
      productionyear: "2008",
      testedproductionyear: "",
      alcoholstrength: "14.5%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8961108",
      articleid: "596810",
      articletype: "89611",
      name: "Escapades",
      name2: "Shiraz",
      priceinclvat: "799.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2011-08-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Western Cape, Coastal Region, Stellenbos",
      countryoforiginlandname: "Sydafrika",
      producer: "Escapade Winery",
      provider: "Carovin AB",
      productionyear: "2008",
      testedproductionyear: "",
      alcoholstrength: "14.5%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "7637201",
      articleid: "800116",
      articletype: "76372",
      name: "Sangiovese",
      name2: "Riserva",
      priceinclvat: "181.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-11-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Emilia-Romagna, Sangiovese di Romagna",
      countryoforiginlandname: "Italien",
      producer: "Umberto Cesari",
      provider: "Hjo Grosshandel AB",
      productionyear: "2010",
      testedproductionyear: "",
      alcoholstrength: "13%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "7638601",
      articleid: "800523",
      articletype: "76386",
      name: "Raymond",
      name2: "R Collection Zinfandel",
      priceinclvat: "105.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-11-01",
      finaldelivery: " ",
      category: "R\u00c3\u00b6tt vin",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Kalifornien",
      countryoforiginlandname: "USA",
      producer: "Raymond Vineyard & Cellar",
      provider: "Enjoy Wine & Spirits AB",
      productionyear: "2011",
      testedproductionyear: "",
      alcoholstrength: "14.5%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "7799701",
      articleid: "802465",
      articletype: "77997",
      name: "Jacquinot",
      name2: "Symphonie Mill\u00c3\u00a9sime Brut",
      priceinclvat: "499.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-11-01",
      finaldelivery: " ",
      category: "Mousserande vin, Vitt torrt",
      packaging: "Flaska",
      captype: "Naturkork",
      countryoforigin: "Champagne",
      countryoforiginlandname: "Frankrike",
      producer: "Jacquinot & Fils",
      provider: "Convino",
      productionyear: "2002",
      testedproductionyear: "",
      alcoholstrength: "12%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    }
  ],
  spirits: [
    {
      nr: "3036004",
      articleid: "633368",
      articletype: "30360",
      name: "Armagnac de Montal",
      name2: "",
      priceinclvat: "4297.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2012-03-29",
      finaldelivery: " ",
      category: "Armagnac",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Armagnac",
      countryoforiginlandname: "Frankrike",
      producer: "Armagnac Montal",
      provider: "Symposion International AB",
      productionyear: "1912",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "TSE",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8303202",
      articleid: "799576",
      articletype: "83032",
      name: "Wista H\u00c3\u00a4rads",
      name2: "Apel",
      priceinclvat: "525.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2013-11-01",
      finaldelivery: " ",
      category: "\u00c3\u2013vrig sprit",
      packaging: "Flaska",
      captype: "",
      countryoforigin:
        "J\u00c3\u00b6nk\u00c3\u00b6pings l\u00c3\u00a4n, J\u00c3\u00b6nk\u00c3\u00b6pings kommun",
      countryoforiginlandname: "Sverige",
      producer: "Vistakulle Fruktodling",
      provider: "Per Knutsson Vistakullefruktod",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8653401",
      articleid: "506700",
      articletype: "86534",
      name: "Glen Mhor",
      name2: "26 Years",
      priceinclvat: "1364.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2010-07-01",
      finaldelivery: " ",
      category: "Whisky, Malt",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Skottland, Highlands, Speyside",
      countryoforiginlandname: "Storbritannien",
      producer: "John Milroy",
      provider: "Clydesdale AB",
      productionyear: "1982",
      testedproductionyear: "",
      alcoholstrength: "46%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8653604",
      articleid: "648911",
      articletype: "86536",
      name: "Promenade en Cognac",
      name2: "",
      priceinclvat: "729.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2012-03-01",
      finaldelivery: " ",
      category: "Cognac",
      packaging: "3 fl \u00c3\u00a0 200 ml",
      captype: "",
      countryoforigin: "Cognac",
      countryoforiginlandname: "Frankrike",
      producer: "L\u00c3\u00a9opold Gourmel",
      provider: "Bibendum",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "42%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8654202",
      articleid: "570582",
      articletype: "86542",
      name: "Bepi Tosolini",
      name2: "Grappa Prosecco",
      priceinclvat: "448.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2011-04-01",
      finaldelivery: " ",
      category: "Grappa och Marc, Grappa",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Italien",
      producer: "Bepi Tosolini",
      provider: "Osteria Goteborg AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8654301",
      articleid: "879464",
      articletype: "86543",
      name: "Normandin Mercier",
      name2: "Petite Champagne VSOP",
      priceinclvat: "619.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2014-08-01",
      finaldelivery: " ",
      category: "Cognac",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Cognac, Petite Champagne",
      countryoforiginlandname: "Frankrike",
      producer: "Normandin-Mercier",
      provider: "Jakobsson och S\u00c3\u00b6derstr\u00c3\u00b6m AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8654402",
      articleid: "320260",
      articletype: "86544",
      name: "De Kuyper",
      name2: "Wild Strawberry",
      priceinclvat: "152.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2008-04-01",
      finaldelivery: " ",
      category: "Lik\u00c3\u00b6r, Frukter och b\u00c3\u00a4r",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Nederl\u00c3\u00a4nderna",
      producer: "De Kuyper",
      provider: "Nigab",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "23%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8655002",
      articleid: "841570",
      articletype: "86550",
      name: "Jarzebiak R\u00c3\u00b6nnb\u00c3\u00a4r",
      name2: "",
      priceinclvat: "249.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2014-04-01",
      finaldelivery: " ",
      category: "Kryddad sprit",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Polen",
      producer: "AWW",
      provider: "AIS Alcohol Import for Scandin",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8655101",
      articleid: "563443",
      articletype: "86551",
      name: "Bowmore",
      name2: "Scott's Selection",
      priceinclvat: "989.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2011-03-01",
      finaldelivery: " ",
      category: "Whisky, Malt",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Skottland, Islay",
      countryoforiginlandname: "Storbritannien",
      producer: "Speyside Distillery",
      provider: "Granqvist Beverage House AB",
      productionyear: "1989",
      testedproductionyear: "",
      alcoholstrength: "51.4%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8655201",
      articleid: "434564",
      articletype: "86552",
      name: "Tullamore Dew",
      name2: "Single Malt 10 Years",
      priceinclvat: "399.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2010-02-01",
      finaldelivery: " ",
      category: "Whisky, Malt",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "",
      countryoforiginlandname: "Irland",
      producer: "Tullamore Dew",
      provider: "Nigab",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "40%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    },
    {
      nr: "8655401",
      articleid: "376962",
      articletype: "86554",
      name: "Arette",
      name2: "Blanco",
      priceinclvat: "399.00",
      volumeml: null,
      priceperlitre: null,
      introduced: "2009-04-01",
      finaldelivery: " ",
      category: "Tequila och Mezcal",
      packaging: "Flaska",
      captype: "",
      countryoforigin: "Jalisco",
      countryoforiginlandname: "Mexiko",
      producer: "Azteca de Jalisco",
      provider: "AliasSmith AB",
      productionyear: "",
      testedproductionyear: "",
      alcoholstrength: "38%",
      module: "",
      assortment: "BS",
      organic: "0",
      kosher: "0"
    }
  ]
};